mutation UpsertUser($email: String!, $username: String, $photoUrl: String) @auth(level: USER) {
  user_upsert(data: {
    id_expr: "auth.uid"
    email: $email,
    username: $username,
    photoUrl: $photoUrl
  })
}

mutation UpdateFcmToken($token: String!) @auth(level: USER) {
  user_update(id_expr: "auth.uid", data: { fcmToken: $token })
}

mutation CreateReport($category: String!, $desc: String, $lat: Float!, $lng: Float!)@auth(level: USER){
    report_insert(data: {
        userId_expr: "auth.uid"
        categoryId: $category,
        description: $desc,
        latitude: $lat,
        longitude: $lng,
    })
}

mutation AddPhoto($reportId: UUID!, $url: String!) @auth(level: USER) {
  reportPhoto_insert(data: {
    reportId: $reportId,
    imageUrl: $url
  })
}

mutation RemoveReportPhoto($photoId: UUID!) @auth(level: USER) {
  reportPhoto_deleteMany(where: {
    id: { eq: $photoId }
    report: { userId: { eq_expr: "auth.uid" } }
  })
}

mutation UpvoteReport($reportId: UUID!) @auth(level: USER) {
  upvote_insert(data: {
    userId_expr: "auth.uid"
    reportId: $reportId
  })
}

mutation RemoveUpvote($reportId: UUID!) @auth(level: USER) {
  upvote_deleteMany(where: {
    reportId: { eq: $reportId }
    userId: { eq_expr: "auth.uid" }
  })
}

mutation AddComment($reportId: UUID!, $content: String!) @auth(level: USER) {
  comment_insert(data: {
    reportId: $reportId
    userId_expr: "auth.uid"
    content: $content
  })
}

mutation EditComment($commentId: UUID!, $content: String!) @auth(level: USER) {
  comment_update(id: $commentId, data: {
    content: $content
  })
}

mutation DeleteComment($commentId: UUID!) @auth(level: USER) {
  comment_delete(id: $commentId)
}

mutation EditReport(
  $reportId: UUID!,
  $category: String!,
  $desc: String,
  $lat: Float!,
  $lng: Float!
) @auth(level: USER) {
  report_updateMany(
    where: {
      id: { eq: $reportId }
      userId: { eq_expr: "auth.uid" }
    }
    data: {
      categoryId: $category
      description: $desc
      latitude: $lat
      longitude: $lng
    }
  )
}

mutation DeleteReport($reportId: UUID!) @auth(level: USER) {
  comment_deleteMany(where: {
    reportId: { eq: $reportId }
    report: { userId: { eq_expr: "auth.uid" } }
  })
  upvote_deleteMany(where: {
    reportId: { eq: $reportId }
    report: { userId: { eq_expr: "auth.uid" } }
  })
  reportPhoto_deleteMany(where: {
    reportId: { eq: $reportId }
    report: { userId: { eq_expr: "auth.uid" } }
  })
  report_deleteMany(where: {
    id: { eq: $reportId }
    userId: { eq_expr: "auth.uid" }
  })
}

mutation DeleteAccount @auth(level: USER) @transaction {
  comment_deleteMany(where: {
    _or: [
      { userId: { eq_expr: "auth.uid" } },
      { report: { userId: { eq_expr: "auth.uid" } } }
    ]
  })
  upvote_deleteMany(where: {
    _or: [
      { userId: { eq_expr: "auth.uid" } },
      { report: { userId: { eq_expr: "auth.uid" } } }
    ]
  })
  reportPhoto_deleteMany(where: {
    report: { userId: { eq_expr: "auth.uid" } }
  })
  report_deleteMany(where: {
    userId: { eq_expr: "auth.uid" }
  })
  user_delete(key: { id_expr: "auth.uid" })
}