# Pobieranie wszystkich zgłoszeń na mapę
query GetReports @auth(level: PUBLIC) {
  reports {
    id
    latitude
    longitude
    description
    status
    createdAt
    category {
      name
      iconName
      pinColor
    }
    reportPhotos_on_report {
      id
      imageUrl
    }
    upvotes_on_report {
      id
      user {
        id
      }
    }
  }
}

# Pobieranie niezakończonych zgłoszeń
query GetActiveReports @auth(level: PUBLIC) {
  reports(where: { status: { ne: "ZAKONCZONE" } }) {
    id
    latitude
    longitude
    description
    status
    createdAt
    category {
      name
      iconName
      pinColor
    }
    reportPhotos_on_report {
      id
      imageUrl
    }
    upvotes_on_report {
      id
      user {
        id
      }
    }
  }
}

# Pobieranie zgłoszeń zalogowanego użytkownika
query GetMyReports @auth(level: USER) {
  reports(where: { userId: { eq_expr: "auth.uid" } }) {
    id
    latitude
    longitude
    description
    status
    createdAt
    category {
      name
      iconName
      pinColor
    }
    reportPhotos_on_report {
      id
      imageUrl
    }
    upvotes_on_report {
      id
      user {
        id
      }
    }
    user {
      id
    }
  }
}

# Pobieranie listy kategorii
query GetCategories @auth(level: PUBLIC) {
  categories {
    id
    name
    iconName
    pinColor
  }
}

query GetReportComments($reportId: UUID!) @auth(level: PUBLIC) {
  comments(where: { reportId: { eq: $reportId } }) {
    id
    content
    createdAt
    user {
      id
      username
      photoUrl
    }
  }
}