extend type Comment {
  """
  ✨ Implicit foreign key field based on `Comment`.`report`. It must match the value of `Report`.`id`. See `@ref` for how to customize it.
  """
  reportId: UUID! @fdc_generated(from: "Comment.report", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Comment`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Comment.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Report {
  """
  ✨ Implicit foreign key field based on `Report`.`category`. It must match the value of `Category`.`id`. See `@ref` for how to customize it.
  """
  categoryId: String! @fdc_generated(from: "Report.category", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Report`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Report.user", purpose: IMPLICIT_REF_FIELD)
}
extend type ReportPhoto {
  """
  ✨ Implicit foreign key field based on `ReportPhoto`.`report`. It must match the value of `Report`.`id`. See `@ref` for how to customize it.
  """
  reportId: UUID! @fdc_generated(from: "ReportPhoto.report", purpose: IMPLICIT_REF_FIELD)
}
extend type Upvote {
  """
  ✨ Implicit foreign key field based on `Upvote`.`report`. It must match the value of `Report`.`id`. See `@ref` for how to customize it.
  """
  reportId: UUID! @fdc_generated(from: "Upvote.report", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Upvote`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: String! @fdc_generated(from: "Upvote.user", purpose: IMPLICIT_REF_FIELD)
}
