extend type Query {
  """
  ✨ Look up a single `Category` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  category(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Category_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Category_FirstRow
  ): Category @fdc_generated(from: "Category", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Comment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  comment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Comment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Comment_FirstRow
  ): Comment @fdc_generated(from: "Comment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Report` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  report(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Report_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Report_FirstRow
  ): Report @fdc_generated(from: "Report", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ReportPhoto` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  reportPhoto(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ReportPhoto_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReportPhoto_FirstRow
  ): ReportPhoto @fdc_generated(from: "ReportPhoto", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Upvote` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  upvote(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Upvote_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Upvote_FirstRow
  ): Upvote @fdc_generated(from: "Upvote", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Category` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  categories(
    """
    Filter condition to narrow down the query results.
    """
    where: Category_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Category_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Category_Having
  ): [Category!]! @fdc_generated(from: "Category", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Comment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  comments(
    """
    Filter condition to narrow down the query results.
    """
    where: Comment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Comment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Comment_Having
  ): [Comment!]! @fdc_generated(from: "Comment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Report` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  reports(
    """
    Filter condition to narrow down the query results.
    """
    where: Report_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Report_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Report_Having
  ): [Report!]! @fdc_generated(from: "Report", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ReportPhoto` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  reportPhotos(
    """
    Filter condition to narrow down the query results.
    """
    where: ReportPhoto_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ReportPhoto_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ReportPhoto_Having
  ): [ReportPhoto!]! @fdc_generated(from: "ReportPhoto", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Upvote` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  upvotes(
    """
    Filter condition to narrow down the query results.
    """
    where: Upvote_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Upvote_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Upvote_Having
  ): [Upvote!]! @fdc_generated(from: "Upvote", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
